# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b1c3a9f1877b36c8fa5d2dc89e766d47443062782962ee88500b57d46e4108f1e338664f3dbe781bc23b3eef057c429cb276aa13a4a05553bf9125fcd9c7a99e

test:
  secret_key_base: f7484ca6595564debb3750d7f1e918ddf4473491ebe3f1868a4751c44474179f61ad386dc3998093cf948f5d00d50460f8e384c11bc6bbc37bc2d54228ae07ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
